@startuml

skinparam classFontStyle bold
skinparam classFontSize 18
skinparam classFontName Courier
skinparam objectStereotypeFontStyle  bold

abstract class BaseSpider {
    **int** timeout
    **queue[str]** queue
    **int** max_entries
    **str** start_URL
    **void** crawl()
    **DOM** __parse(str)
    **Iterable[str]** __URLs(DOM)
}

abstract class BaseAsyncSpider extends BaseSpider {


}

class AsyncSpider extends BaseAsyncSpider {

}

@enduml
